In [51]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
# from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, f1_score,precision_score,recall_score


In [97]:
data1=pd.read_csv('10ms_all_erp.csv')
data1=np.asarray(data1)
Y=data1[:,1]
X=data1[:,1:]
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=101)

print(X_train.shape)
print(y_train.shape)
print(y_test.shape)
print(X_test.shape)

(2534, 1429)
(2534,)
(1249,)
(1249, 1429)


In [98]:
clf = SVC(C=1,kernel='rbf')
clf.fit(X_train, y_train)
y_pred =clf.predict(X_test)
print'classification_report\n',classification_report(y_test, y_pred)
print'Confusion Matrix\n',confusion_matrix(y_test, y_pred)

classification_report
             precision    recall  f1-score   support

        0.0       0.99      0.91      0.95       526
        1.0       0.94      0.99      0.97       723

avg / total       0.96      0.96      0.96      1249

Confusion Matrix
[[480  46]
 [  5 718]]


In [99]:
clf.score(X_test, y_test)

0.9591673338670936

In [100]:
clf = SVC(C=1,kernel='linear')
clf.fit(X_train, y_train)
y_pred =clf.predict(X_test)
print'classification_report\n',classification_report(y_test, y_pred)
print'Confusion Matrix\n',confusion_matrix(y_test, y_pred)

classification_report
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       526
        1.0       1.00      1.00      1.00       723

avg / total       1.00      1.00      1.00      1249

Confusion Matrix
[[526   0]
 [  0 723]]


In [101]:
clf.score(X_test, y_test)

1.0

In [104]:
cc1=data1[:,2:]
cc1[:,0]

array([1.34853552e-10, 5.23752825e-10, 4.58518788e-10, ...,
       1.21614813e-10, 4.24138422e-10, 7.42952014e-10])

In [105]:
cc1=data1[:,1:]
cc1[:,0]

array([0., 0., 0., ..., 1., 1., 1.])