In [122]:
# import all dependencies
%matplotlib inline
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, metrics

In [123]:
from sklearn.datasets import load_digits
digits = load_digits()
Xhand=digits.data
labels=digits.target
Xhand.shape
# np.unique(labels)

(1797, 64)

In [124]:
X_train, X_test, y_train, y_test = train_test_split(Xhand, labels, test_size=0.25, random_state=0)

In [125]:
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)  

In [127]:
lda = LDA()  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)

In [128]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [129]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 29  9  0  1  0  0  0  3  1]
 [ 0  0 44  0  0  0  0  0  0  0]
 [ 0  0  4 33  2  0  1  0  5  0]
 [ 0  2  0  0 33  1  1  1  0  0]
 [ 0  0  0  0  0 42  2  1  1  2]
 [ 0  0  1  0  1  1 49  0  0  0]
 [ 0  0  1  2  0  0  0 45  0  0]
 [ 0 17  3  0  0  0  1  0 22  5]
 [ 0  0  1  1  0  0  0  2 10 33]]
Accuracy0.8155555555555556


In [130]:
X_test.shape

(450, 9)

# [LDA](https://stackabuse.com/implementing-lda-in-python-with-scikit-learn/) on IRIS data

In [82]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']  
dataset = pd.read_csv(url, names=names)
#dataset

In [83]:
X = dataset.iloc[:, 0:4].values  
y = dataset.iloc[:, 4].values  

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

In [85]:
lda = LDA(n_components=5)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)
X_test.shape

(30, 2)

In [86]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test) 

In [87]:
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred)))  

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Accuracy0.9666666666666667


# SVM

In [89]:
cv=5
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf','poly','sigmoid'), 'C':[1, 10,100,1000],'gamma':[0.01,.002,0.003]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=cv)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ('linear', 'rbf', 'poly', 'sigmoid'), 'C': [1, 10, 100, 1000], 'gamma': [0.01, 0.002, 0.003]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [90]:
clf.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.002, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [98]:
pred=clf.best_estimator_.predict(X_test)
clf.score(X_test, y_test)  
print pred
# print y_test

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa']


In [92]:
conf_mat=confusion_matrix(y_test,pred)
conf_mat

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]])

In [93]:
acc=accuracy_score(clf.best_estimator_.predict(X_test),y_test)
print acc

1.0


In [94]:
from sklearn.metrics import classification_report
#target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

