# Shuffle and hyperparameters Tuning for hearing data set [Cross-validation](http://scikit-learn.org/stable/modules/cross_validation.html)

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm, metrics,preprocessing
#from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve, auc
from matplotlib import pyplot as plt
from collections import Counter
from scipy.stats import norm
import seaborn as sns; sns.set(font_scale=1.2)
%matplotlib inline

# load the dataset

In [2]:
#path='C:/Users/Sultan/OneDrive - The University of Memphis/RESEARCH2017S/Hearing_data/Graph_Braph/WUpclean13/indidivual/Nodalfeatures_Clean_LH_wup.csv'
path='/home/sultan/SVM_Graph_theory/0_Python_final_SVM_Graph_theory/WUpclean13/indidivual/Nodalfeatures_Clean_LH_wup.csv'
dataset =pd.read_csv(path)

In [3]:
#sns.lmplot('dia','eccen',data=dataset,hue='class',palette='Set1',fit_reg=False,scatter_kws={"s":70})

# split the data set

In [4]:
Xc=dataset.iloc[:,2:6].values
y=dataset.iloc[:,6].values
X=preprocessing.scale(Xc)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.20, random_state=40)     

# see the shape of the traing and test data set

In [6]:
#X_train.shape, y_train.shape
X_test.shape, y_test.shape   

((7, 4), (7,))

In [23]:
# X_test,y_test

# Find the Class labels

In [8]:
np.unique(y_test)

array([0, 1])

# Find the repeated class number 

In [9]:
np.unique(y_test,return_counts=True)

(array([0, 1]), array([3, 4]))

# Gridserach CV

In [10]:
# cv=5
# from sklearn.model_selection import GridSearchCV
# parameters = {'kernel':('linear', 'rbf','poly','sigmoid'), 'C':[1, 10,100,1000],'gamma':[0.01,.002,0.003]}
# svc = svm.SVC()
# clf = GridSearchCV(svc, parameters,cv=cv)
# clf.fit(X_train, y_train)

In [11]:
cv=5
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':['rbf'], 'C':[1, 10,100,1000],'gamma':[0.01,.02,0.03]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=cv)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ['rbf'], 'C': [1, 10, 100, 1000], 'gamma': [0.01, 0.02, 0.03]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [12]:
#print clf.cv_results_
#clf.best_estimator_

# Find the best parameters  

In [13]:
clf.best_estimator_

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.02, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
pred=clf.best_estimator_.predict(X_test)
clf.score(X_test, y_test)  
print pred
print y_test

[1 0 1 0 1 0 0]
[1 1 1 0 1 0 0]


In [15]:
acc=accuracy_score(clf.best_estimator_.predict(X_test),y_test)
print acc

0.8571428571428571


In [16]:
conf_mat=confusion_matrix(y_test,pred)
conf_mat

array([[3, 0],
       [1, 3]])

In [17]:
from sklearn.metrics import classification_report
#target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.75      1.00      0.86         3
          1       1.00      0.75      0.86         4

avg / total       0.89      0.86      0.86         7



 # [ROC Curve](https://datamize.wordpress.com/2015/01/24/how-to-plot-a-roc-curve-in-scikit-learn/)

In [18]:
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test,pred)
# #false_positive_rate, true_positive_rate, thresholds = metrics.roc_curve(pred, y_test)
# #print false_positive_rate
# roc_auc = auc(false_positive_rate, true_positive_rate)
# #print 'FPR=',false_positive_rate,'\n','TPR=',true_positive_rate
# fig,ax1=plt.subplots(ncols=1)
# ax1.plot(false_positive_rate, true_positive_rate, 'b-', label = 'AUC = %0.2f' % roc_auc)
# ax1.legend(loc = 'lower right')
# ax1.plot([0, 1], [0, 1],'r--')
# ax1.set_xlim([0, 1])
# ax1.set_ylim([0, 1])
# ax1.set_ylabel('True Positive Rate')
# ax1.set_xlabel('False Positive Rate')
# ax1.set_title('Receiver Operating Characteristic')

In [19]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test,pred)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.875