# Shuffle and hyperparameters Tuning for hearing data set [Cross-validation](http://scikit-learn.org/stable/modules/cross_validation.html)

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm, metrics,preprocessing
#from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve, auc
from matplotlib import pyplot as plt
from collections import Counter
from scipy.stats import norm
import seaborn as sns; sns.set(font_scale=1.2)
%matplotlib inline

# load the dataset

In [2]:
#path='C:/Users/Sultan/OneDrive - The University of Memphis/RESEARCH2017S/Hearing_data/Graph_Braph/WUpclean13/indidivual/glonodal_all_featureswup.csv'
path='/home/sultan/SVM_Graph_theory/0_Python_final_SVM_Graph_theory/WUpclean13/indidivual/glonodal_all_featureswup.csv'
dataset =pd.read_csv(path)

In [3]:
dataset.head()

Sl no.  Participant ID     dia   eccen  char.pat      A1      M1      B1  \
0       1               4  8.5946  7.5441    3.8932  8.3543  8.2290  8.1959   
1       2               5  8.3757  7.4463    3.9192  7.2686  7.5563  7.6873   
2       3               6  7.3124  6.3991    3.4827  6.7691  7.3124  6.5431   
3       4               7  8.0385  7.1105    3.7195  6.4555  6.8791  6.8827   
4       5              11  6.7112  6.0379    3.3474  5.9439  6.2559  6.2719   

       B2    A1.1    M1.1    B1.1    B2.1  class  
0  8.3335  8.1509  6.3674  7.3810  8.1245      1  
1  7.6985  7.7089  6.2121  7.4025  7.7550      1  
2  6.8448  6.7108  5.9035  6.4910  6.4976      1  
3  7.0433  8.0385  7.9529  7.2204  7.2955      1  
4  6.2264  5.8560  5.4365  5.8820  5.8935      1

In [4]:
#sns.lmplot('dia','eccen',data=dataset,hue='class',palette='Set1',fit_reg=False,scatter_kws={"s":70})

# split the data set

In [5]:
Xc=dataset.iloc[:,2:13].values
y=dataset.iloc[:,13].values
X=preprocessing.scale(Xc)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(Xc,y, test_size=.20, random_state=40)     

# see the shape of the traing and test data set

In [7]:
#X_train.shape, y_train.shape
X_test.shape, y_test.shape   

((7, 11), (7,))

In [8]:
X_test,y_test

(array([[7.3124, 6.3991, 3.4827, 6.7691, 7.3124, 6.5431, 6.8448, 6.7108,
         5.9035, 6.491 , 6.4976],
        [7.1817, 6.3646, 3.3914, 6.5009, 6.2453, 6.3744, 6.4167, 6.1618,
         6.4142, 6.2349, 6.0749],
        [7.9622, 6.8359, 3.8255, 6.7502, 7.0546, 6.9224, 6.9974, 7.0873,
         6.7193, 6.9056, 6.9625],
        [6.3699, 5.9452, 3.2354, 5.7528, 5.9171, 6.0588, 5.7579, 6.1177,
         5.6298, 5.6686, 5.7223],
        [7.7771, 6.6604, 3.6813, 7.6655, 7.0895, 6.3905, 6.5908, 6.9728,
         6.7016, 6.8161, 6.7357],
        [6.6464, 6.0996, 3.3267, 5.9904, 6.3201, 5.9709, 6.1841, 6.1781,
         6.0742, 6.1076, 6.1064],
        [7.0875, 6.1273, 3.3422, 5.9385, 6.1982, 5.8915, 6.1209, 5.886 ,
         6.0396, 6.2291, 6.1752]]), array([1, 1, 1, 0, 1, 0, 0]))

# Find the Class labels

In [9]:
np.unique(y_test)

array([0, 1])

# Find the repeated class number 

In [10]:
np.unique(y_test,return_counts=True)

(array([0, 1]), array([3, 4]))

# Gridserach CV

In [11]:
cv=5
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf','poly'), 'C':[1, 10,100,1000],'gamma':[0.001,.002,0.003]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=cv)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ('linear', 'rbf', 'poly'), 'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.002, 0.003]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [12]:
# cv=5
# from sklearn.model_selection import GridSearchCV
# parameters = {'kernel':['rbf'], 'C':[1, 10,100],'gamma':[0.01,.02,0.03]}
# svc = svm.SVC()
# clf = GridSearchCV(svc, parameters,cv=cv)
# clf.fit(X_train, y_train)

In [13]:
#print clf.cv_results_
#clf.best_estimator_

# Find the best parameters  

In [14]:
clf.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
pred=clf.best_estimator_.predict(X_test)
#clf.score(X_test, y_test)  
print pred
print y_test

[1 0 1 0 1 0 0]
[1 1 1 0 1 0 0]


In [16]:
acc=accuracy_score(clf.best_estimator_.predict(X_test),y_test)
print acc

0.8571428571428571


In [17]:
conf_mat=confusion_matrix(y_test,pred)
conf_mat

array([[3, 0],
       [1, 3]])

In [18]:
from sklearn.metrics import classification_report
#target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.75      1.00      0.86         3
          1       1.00      0.75      0.86         4

avg / total       0.89      0.86      0.86         7



 # [ROC Curve](https://datamize.wordpress.com/2015/01/24/how-to-plot-a-roc-curve-in-scikit-learn/)

In [19]:
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test,pred)
# #false_positive_rate, true_positive_rate, thresholds = metrics.roc_curve(pred, y_test)
# #print false_positive_rate
# roc_auc = auc(false_positive_rate, true_positive_rate)
# #print 'FPR=',false_positive_rate,'\n','TPR=',true_positive_rate
# fig,ax1=plt.subplots(ncols=1)
# ax1.plot(false_positive_rate, true_positive_rate, 'b-', label = 'AUC = %0.2f' % roc_auc)
# ax1.legend(loc = 'lower right')
# ax1.plot([0, 1], [0, 1],'r--')
# ax1.set_xlim([0, 1])
# ax1.set_ylim([0, 1])
# ax1.set_ylabel('True Positive Rate')
# ax1.set_xlabel('False Positive Rate')
# ax1.set_title('Receiver Operating Characteristic')

In [20]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test,pred)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

0.875